# Generated by Django 4.0.3 on 2022-05-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
