# Generated by Django 4.0.3 on 2022-05-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_rename_review_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
