# Generated by Django 4.0.4 on 2022-05-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0007_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
