# Generated by Django 4.0.4 on 2022-05-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0008_watchlist_avg_rating_watchlist_num_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='num_ratings',
            new_name='number_of_ratings',
        ),
    ]
